### ISSUE TITLE
Add SMS alert sending prior to sending results

### ISSUE THREAD

**Issue by sanjiva** [ECLK/Results-Dist#32]

**Comment by chamil321** [comment]
Flow of the SMS delivery

Distributor startup
- Load mobile nos that are persisted in the db to in-memory array

Registration 
- Register at a public URL by sending GET request along with the mobile no. Eg: /sms/94771234567 
- Ideamart request to have 94 prefix
- Sanitize mobile no
- Update the in-memory array and persist in a table of the same subscription db

De registration 
- De register at a public URL by sending DELETE request along with the mobile no. Eg: /sms/94771234567 
- Ideamart request to have 94 prefix
- Sanitize mobile no
- Remove it from the in-memory array and db table of the same subscription db

Delivery 
- Once the result data available, iterate in-memory array and send sms 
- Retry only possible status codes once- should we try more?

Clarification needed
- Do we need to cater international mobile nos? If so Ideamart API will not be sufficient. According to their documentation, they expect mobile in “tel:94771234567” format. 
- We may require a dialog no as the source to create our API in Ideamart. ATM we have tested impl using a simulator and we will do another round after provisioning API at Ideamart 
- If we require sms to be delivered before resource distribution, we may need to take out the sms logic out from the smsWorker
- We got following low level error(compatibility issue) while integrating ideamart connector with distributor. We could resolve it after migrating to ballerina 1.0.3-SNAPSHOT. Do we have plan to use 1.0.3 if it released soon?
> error: org.wso2.ballerinalang.compiler.bir.writer.CPEntry$StringCPEntry cannot be cast to org.wso2.ballerinalang.compiler.bir.writer.CPEntry$PackageCPEntry

**Comment by sanjiva** [comment]
Also  push out a "results arriving" notice via websub to all subscribers

**Comment by sanjiva** [comment]
Answers:
- Registration & deregistration:
  - Lets assume that's offline - one way or the other the numbers are in the DB and you load it at startup. If the DB changes we can either restart or have a simple service way to refresh the in-memory list.

- Delivery:
  - Lets not do any retries; if it fails tough.

- Service provider:
  - Per our chat we'll go with LSF's Twillio accont for simplicity and convenience.

**Comment by chamil321** [comment]
> Answers:
> 
> * Registration & deregistration:
>   
>   * Lets assume that's offline - one way or the other the numbers are in the DB and you load it at startup. If the DB changes we can either restart or have a simple service way to refresh the in-memory list.

Should we keep another service other than the website service? I added the API for now to the website, I'll move it to another service if necessary (https://github.com/ECLK/Results-Dist/pull/81/files#diff-23a02492b8512ee4547b798c5c549d3dR192)

> * Delivery:
>   
>   * Lets not do any retries; if it fails tough.

Ack
> * Service provider:
>   
>   * Per our chat we'll go with LSF's Twillio accont for simplicity and convenience.

Ack

We'll send a separate PR to push out "results arriving" notice via websub to all subscribers
