### ISSUE TITLE
How do you scale websub hub?

### ISSUE THREAD

**Issue by sanjiva** [ECLK/Results-Dist#35]
We don't have an issue right now as the expected number of subscribers is ~100, but the current implementation of the websub hub in Ballerina doesn't seem to scale for me as I don't see how we can run multiple instances to run at once.

The DB backend is simply a store and it seems the hub is keeping all the subscribers in memory (and reloading at startup). 

If you agree, please create an issue in the websub hub code and close this off. We can discuss it there and see what the right way to design a scaling model.

**Comment by MaryamZi** [comment]
Yeah this should be a generic issue. Created an issue for `ballerina:websub`.
