### ISSUE TITLE
JAR doesn't work with latest openJDK JRE version (13.0.1)

### ISSUE THREAD

**Issue by hiranya** [ECLK/Results-Dist#74]
The JAR is not executable using the latest OpenJDK 13.0.1 on Mac. Hangs with the below warning;
```
hiranyas-mbp:LSF hiranya$ java -jar subscriber-20191102.jar "hiranya-secret" -port=1234 -myURL=http://****.ngrok.io
WARNING: Incompatible JRE version '13.0.1' found. This ballerina program supports running on JRE version '1.8.*'
```
Version tested is;
```
hiranyas-mbp:LSF hiranya$ java -version
openjdk version "13.0.1" 2019-10-15
OpenJDK Runtime Environment (build 13.0.1+9)
OpenJDK 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)
```

-------
Works like a charm on OpenJDK 1.8.0 on Ubuntu 18;
```
:~# java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
```

Building from source on JDK 13 could resolve the issue(?). There could be many direct consumers of the provided binaries. If so we might have to provide different builds for their JREs.

**Comment by sanjiva** [comment]
Yes .. its for JDK8 only right now.

I suggest using the openjdk:8 Docker image.

**Comment by sanjiva** [comment]
The code is written in Ballerina BTW .. Ballerina does not yet support the latest JDK.

**Comment by hiranya** [comment]
Gotcha. Closing the issue.
