### ISSUE TITLE
Trying to Run the Subscriber.bal locally which gives Exception in thread "main" java.lang.NullPointerException at org.ballerinalang.tool.Main.main(Main.java:64)

### ISSUE THREAD

**Issue by axewilledge** [ECLK/Results-Dist#76]
I'm trying to run the subscriber with,

> ballerina run .\subscriber.bal "helloworld" -port=1111 -myURL="http://XXXXXXX.ngrok.io"

Which gives me,

> Compiling source
>         subscriber.bal
> Exception in thread "main" java.lang.NullPointerException
>         at org.ballerinalang.tool.Main.main(Main.java:64)

**Comment by axewilledge** [comment]
java -jar subscriber-20191102.jar "your own personal secret" -port=NNNN -myURL="my public URL"

where NNNN is the port that you want this program to open and "my public URL" is the way to get to that port from the internet. For example, if you use ngrok, you'd do "ngrok http NNNN" before this and give the URL that ngrok shows as "my public URL"

**Comment by axewilledge** [comment]
I want to run the subscriber with run command, using below

> ballerina run .\subscriber.bal "helloworld" -port=1111 -myURL="http://XXXXXXX.ngrok.io"

which works with jar file, but above gives me,

> Compiling source
> subscriber.bal
> Exception in thread "main" java.lang.NullPointerException
> at org.ballerinalang.tool.Main.main(Main.java:64)

**Comment by axewilledge** [comment]
>     java -jar subscriber-20191102.jar "your own personal secret" -port=NNNN -myURL="my public URL"

where NNNN is the port that you want this program to open and "my public URL" is the way to get to that port from the internet. For example, if you use ngrok, you'd do "ngrok http NNNN" before this and give the URL that ngrok shows as "my public URL"


Above works okay with jar file but not with source code. Any help?

**Comment by sanjiva** [comment]
Are you trying to modify the code?

**Comment by sanjiva** [comment]
See https://ballerina.io/learn to get started.

**Comment by axewilledge** [comment]
I think I found the issue, I copied the websub module provided in the deployment-utils into my local machine ballerina installation folder. which is now giving me the above error when i import websub.

> import ballerina/websub;

**Comment by axewilledge** [comment]
Is there a way to install that websub module using ballerina cli? Could not find any documents for websub

**Comment by sanjiva** [comment]
Ballerina 1.0.0-2 had not shipped the websub module .. so we had to backdoor it in. There's a release due out today 1.0.3 which has it .. then this hack will go away.

**Comment by axewilledge** [comment]
Can you explain a little how to backdoor that module into ballerina if it can be explained from here? I followed the distributor project and it didn't help that much to understand the process.

**Comment by chamil321** [comment]
@axewilledge Try putting the directories/JARs inside the deployment-utils in to ballerina distribution(same directory structure) in the same order. 
Compatible ballerina version: 1.0.1 [1]

[1] https://ballerina.io/downloads/archived/

**Comment by axewilledge** [comment]
It was the version! It's working now. Needed ballerina version: 1.0.1. Thanks!
